
package cl.clarochile.companyusermanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CompanyUserManagement", targetNamespace = "http://www.clarochile.cl/CompanyUserManagement/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    cl.clarochile.companyusermanagement.ObjectFactory.class,
    cl.clarochile.webservices.schemas.ObjectFactory.class
})
public interface CompanyUserManagement {


    /**
     * 
     * @param parameters
     * @return
     *     returns cl.clarochile.companyusermanagement.AddUserResponse
     */
    @WebMethod(operationName = "AddUser", action = "http://www.clarochile.cl/CompanyUserManagement/AddUser")
    @WebResult(name = "AddUserResponse", targetNamespace = "http://www.clarochile.cl/CompanyUserManagement/", partName = "parameters")
    public AddUserResponse addUser(
        @WebParam(name = "AddUserRequest", targetNamespace = "http://www.clarochile.cl/CompanyUserManagement/", partName = "parameters")
        AddUserRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns cl.clarochile.companyusermanagement.EditUserResponse
     */
    @WebMethod(operationName = "EditUser", action = "http://www.clarochile.cl/CompanyUserManagement/EditUser")
    @WebResult(name = "EditUserResponse", targetNamespace = "http://www.clarochile.cl/CompanyUserManagement/", partName = "parameters")
    public EditUserResponse editUser(
        @WebParam(name = "EditUserRequest", targetNamespace = "http://www.clarochile.cl/CompanyUserManagement/", partName = "parameters")
        EditUserRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns cl.clarochile.companyusermanagement.DeleteUserResponse
     */
    @WebMethod(operationName = "DeleteUser", action = "http://www.clarochile.cl/CompanyUserManagement/DeleteUser")
    @WebResult(name = "DeleteUserResponse", targetNamespace = "http://www.clarochile.cl/CompanyUserManagement/", partName = "parameters")
    public DeleteUserResponse deleteUser(
        @WebParam(name = "DeleteUserRequest", targetNamespace = "http://www.clarochile.cl/CompanyUserManagement/", partName = "parameters")
        DeleteUserRequest parameters);

}
