
package cl.clarochile.companyusermanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CompanyUserManagement", targetNamespace = "http://www.clarochile.cl/CompanyUserManagement/", wsdlLocation = "file:/home/luis/HAVAS/CargaInicialEmpresas/wscompany/CompanyUserManagement.wsdl")
public class CompanyUserManagement_Service
    extends Service
{

    private final static URL COMPANYUSERMANAGEMENT_WSDL_LOCATION;
    private final static WebServiceException COMPANYUSERMANAGEMENT_EXCEPTION;
    private final static QName COMPANYUSERMANAGEMENT_QNAME = new QName("http://www.clarochile.cl/CompanyUserManagement/", "CompanyUserManagement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/luis/HAVAS/CargaInicialEmpresas/wscompany/CompanyUserManagement.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPANYUSERMANAGEMENT_WSDL_LOCATION = url;
        COMPANYUSERMANAGEMENT_EXCEPTION = e;
    }

    public CompanyUserManagement_Service() {
        super(__getWsdlLocation(), COMPANYUSERMANAGEMENT_QNAME);
    }

    public CompanyUserManagement_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPANYUSERMANAGEMENT_QNAME, features);
    }

    public CompanyUserManagement_Service(URL wsdlLocation) {
        super(wsdlLocation, COMPANYUSERMANAGEMENT_QNAME);
    }

    public CompanyUserManagement_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPANYUSERMANAGEMENT_QNAME, features);
    }

    public CompanyUserManagement_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompanyUserManagement_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompanyUserManagement
     */
    @WebEndpoint(name = "CompanyUserManagementSOAP")
    public CompanyUserManagement getCompanyUserManagementSOAP() {
        return super.getPort(new QName("http://www.clarochile.cl/CompanyUserManagement/", "CompanyUserManagementSOAP"), CompanyUserManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompanyUserManagement
     */
    @WebEndpoint(name = "CompanyUserManagementSOAP")
    public CompanyUserManagement getCompanyUserManagementSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.clarochile.cl/CompanyUserManagement/", "CompanyUserManagementSOAP"), CompanyUserManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPANYUSERMANAGEMENT_EXCEPTION!= null) {
            throw COMPANYUSERMANAGEMENT_EXCEPTION;
        }
        return COMPANYUSERMANAGEMENT_WSDL_LOCATION;
    }

}
